# Generated by Django 3.2.7 on 2024-04-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_class',
            field=models.CharField(default='To do', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_status',
            field=models.CharField(choices=[('To do', 'To do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='To do', max_length=15),
        ),
    ]
