# Generated by Django 3.2.8 on 2024-04-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_course_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
