# Generated by Django 3.2.7 on 2024-04-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20211106_1853'),
        ('organizer', '0003_auto_20211106_2108'),
    ]

    operations = [
    ]
