# Generated by Django 3.2.7 on 2024-04-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_merge_0003_auto_20211106_1853_0003_auto_20211106_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
