# Generated by Django 3.2.9 on 2024-04-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_classnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnote',
            name='lecture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organizer.course'),
            preserve_default=False,
        ),
    ]
