# Generated by Django 3.2.9 on 2024-04-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_remove_classnote_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnote',
            name='lecture',
            field=models.ForeignKey(default='3240', on_delete=django.db.models.deletion.CASCADE, to='organizer.course'),
        ),
    ]
