# Generated by Django 3.2.9 on 2024-04-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_classnote_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnote',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.course'),
        ),
    ]
