# Generated by Django 3.2.9 on 2024-04-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_alter_classnote_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='media/')),
                ('notes_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.course')),
            ],
        ),
    ]
