# Generated by Django 3.2.8 on 2024-04-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_classnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='Name not set', max_length=200),
            preserve_default=False,
        ),
    ]
