# Generated by Django 3.2.7 on 2024-05-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_status',
            field=models.CharField(default='To do', max_length=15),
        ),
    ]
